apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi # Note: GCS FUSE capacity is virtual
  storageClassName: ""
  volumeName: gcs-fuse-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  storageClassName: ""
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: my-gcs-bucket
